### ISSUE TITLE
lazily evaluated

### ISSUE THREAD

**Issue by MarisaKirisame** [lice-lang/lice#1]

**Comment by ice1000** [comment]
Wondering a clearer description

**Comment by MarisaKirisame** [comment]
Functions' results should be lazy evaluated.
Functions' results should be lazily evaluated.
Or better yet,
Functions should be lazy.

**Comment by ice1000** [comment]
but how do I achieve that? Or how should it be like?
4instance:

```lisp
(def square n (* n n))
(def getn (|>
  (println "evaluated")
  (+ 100 200)))
(square (getn))
```

should it print once or twice the word "evaluated"?

If twice, it will be very slow(without saving the result).
If once, it might behave strangely with multi-threading.(Also needs a large refactor)

**Comment by lfkdsk** [comment]
Scheme will print once.

**Comment by ice1000** [comment]
That is to say scheme saves the result of first evaluation, and return the same value afterwards.

**Comment by ice1000** [comment]
Clojure uses lazy evaluation optionally, whether to lazy evaluate or not, depends on you.

**Comment by ice1000** [comment]
I've done a part of it.

+ For conditional clauses(if, while, when), it's lazily evaluated. But in the repl, they'll still be evaluated(because the repl want to print them)
+ For functions, they can't be lazily evaluated because of that fucking dynamic scoping.

**Comment by ice1000** [comment]
@MarisaKirisame So is that acceptable?

**Comment by MarisaKirisame** [comment]
Why Dynamic Scoping than.

**Comment by ice1000** [comment]
Change too many features at the same time would make everything difficult.
I'll do the fucking lambda first.
There should be 3 types of lambdas:
\ is cbv
\\ is cbneed
\\\ is cbname

**Comment by ice1000** [comment]
\\ cbv
\\\\ cbneed
\\\\\\ cbname

**Comment by MarisaKirisame** [comment]
if you have cbneed, you dont need cbname
cbneed can be easily implemented in the language, as long as you have assignment.

**Comment by ice1000** [comment]
That is to say I should change (defexpr) into cbneed, and give up cbname

**Comment by MarisaKirisame** [comment]
Yes.
Another choice is to keep assignment and use cbv, and simulate laziness

**Comment by ice1000** [comment]
Now, defexpr becomes cbneed. cbname is given up.
I used unit test to prove that's true.
So is that acceptable?
If so, I'll close this issue, and go working on lambda.
