### ISSUE TITLE
I hate to tell you this, but...

### ISSUE THREAD

**Issue by cdown** [lice-lang/lice#8]
To most native English speakers, "lice" means "头虱". Not sure if that's what you intended, but it does make me feel icky when I open this repository :-)

**Comment by ice1000** [comment]
But I prefer not changing the name.

+ I named this project when I'm in school, I didn't know the word's meaning and I don't have internet access, I just changed the last two letters of "Lisp".
+ I have made lots of related projects and blogs about Lice, and it's difficult to rename all of them
+ There're also some other programming languages with bad names like BrainF\*ck.
+ I don't know if it's a good idea to start a new project

I do understand the naming issue. However, I'm planning to start working on some other langauges (CovScript and Carvelang) which are of none-icky names.

Just let it go.

**Comment by cdown** [comment]
Sure, just trying to give you a heads up about it :-)
