### ISSUE TITLE
尾递归优化问题怎么解决？

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [lice-lang/lice#9]
这个看起来和 Clojure 类似，Clojure最让我不爽的就是尾递归。同样基于JVM，这个怎么考虑的？

**Comment by ice1000** [comment]
没做。因为是动态作用域，每个名字只有执行到那个位置才知道到底是哪个符号，因此擅自优化是不行的。
这门语言的定义也不是拿来自己编程的，它是一个充当配置的角色，大部分函数应该使用JVM语言通过解释器的API提供。

`undef` 函数可以取消一切函数的定义（甚至包括`def` `if` 这种东西，都是函数，也因此可以被取消定义），也是一个优化的阻碍，我已经在IDE里做了提示了，但是没有在解释器里表现出来。

**Comment by zhengxiaoyao0716** [comment]
好吧果然。JVM做尾递归优化难道无解吗。。。

**Comment by ice1000** [comment]
Kotlin 支持啊。这和JVM无关，这是设计导致的。

**Comment by zhengxiaoyao0716** [comment]
我擦，Kotlin还有这优点
